-- MySQL Script generated by MySQL Workbench
-- 10/05/16 14:18:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(20) NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `lastName2` VARCHAR(45) NULL,
  `idUniversity` INT NULL,
  `phone` INT NULL,
  `address` VARCHAR(45) NULL,
  `timeStamp` DATE NULL,
  `birthday` DATE NULL,
  `isAdmin` BINARY NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DebateTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DebateTypes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DebateTypes` (
  `idDebateTypes` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idDebateTypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DebateRules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DebateRules` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DebateRules` (
  `idDebateRules` INT NOT NULL AUTO_INCREMENT,
  `sections` INT NULL,
  PRIMARY KEY (`idDebateRules`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Debates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Debates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Debates` (
  `idDebates` INT NOT NULL AUTO_INCREMENT,
  `DebateTypes_idDebateTypes` INT NOT NULL,
  `DebateRules_idDebateRules` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `createdDate` DATE NULL,
  `startingDate` DATE NULL,
  `isActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idDebates`),
  INDEX `fk_Debates_DebateTypes1_idx` (`DebateTypes_idDebateTypes` ASC),
  INDEX `fk_Debates_DebateRules1_idx` (`DebateRules_idDebateRules` ASC),
  CONSTRAINT `fk_Debates_DebateTypes1`
    FOREIGN KEY (`DebateTypes_idDebateTypes`)
    REFERENCES `mydb`.`DebateTypes` (`idDebateTypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Debates_DebateRules1`
    FOREIGN KEY (`DebateRules_idDebateRules`)
    REFERENCES `mydb`.`DebateRules` (`idDebateRules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `desciption` VARCHAR(45) NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `lastName2` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `timestamp` DATE NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QualificationRubrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QualificationRubrics` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QualificationRubrics` (
  `idQualificationRubrics` INT NOT NULL,
  `rubricName` VARCHAR(45) NULL,
  `rubricPercentage` VARCHAR(45) NULL,
  `Course_idCourse` INT NOT NULL,
  PRIMARY KEY (`idQualificationRubrics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `idCourse` INT NOT NULL AUTO_INCREMENT,
  `Professor_idProfessor` INT NOT NULL,
  `QualificationRubrics_idQualificationRubrics` INT NOT NULL,
  `finalQualification` DOUBLE NULL,
  `courseCode` VARCHAR(45) NULL,
  PRIMARY KEY (`idCourse`),
  INDEX `fk_Course_Professor1_idx` (`Professor_idProfessor` ASC),
  INDEX `fk_Course_QualificationRubrics1_idx` (`QualificationRubrics_idQualificationRubrics` ASC),
  CONSTRAINT `fk_Course_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_QualificationRubrics1`
    FOREIGN KEY (`QualificationRubrics_idQualificationRubrics`)
    REFERENCES `mydb`.`QualificationRubrics` (`idQualificationRubrics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users_has_Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Course` (
  `Users_idUsers` INT NOT NULL,
  `Course_idCourse` INT NOT NULL,
  PRIMARY KEY (`Users_idUsers`, `Course_idCourse`),
  INDEX `fk_Users_has_Course_Course1_idx` (`Course_idCourse` ASC),
  INDEX `fk_Users_has_Course_Users1_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_Users_has_Course_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Course_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Confirmed_Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Confirmed_Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Confirmed_Users` (
  `Users_idUsers` INT NOT NULL,
  `Debates_idDebates` INT NOT NULL,
  `Role_idRole` INT NOT NULL,
  PRIMARY KEY (`Users_idUsers`, `Debates_idDebates`),
  INDEX `fk_Users_has_Debates_Debates1_idx` (`Debates_idDebates` ASC),
  INDEX `fk_Users_has_Debates_Users1_idx` (`Users_idUsers` ASC),
  INDEX `fk_Users_has_Debates_Role1_idx` (`Role_idRole` ASC),
  CONSTRAINT `fk_Users_has_Debates_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Debates_Debates1`
    FOREIGN KEY (`Debates_idDebates`)
    REFERENCES `mydb`.`Debates` (`idDebates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Debates_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Debates_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Debates_has_Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Debates_has_Course` (
  `Debates_idDebates` INT NOT NULL,
  `Course_idCourse` INT NOT NULL,
  PRIMARY KEY (`Debates_idDebates`, `Course_idCourse`),
  INDEX `fk_Debates_has_Course_Course1_idx` (`Course_idCourse` ASC),
  INDEX `fk_Debates_has_Course_Debates1_idx` (`Debates_idDebates` ASC),
  CONSTRAINT `fk_Debates_has_Course_Debates1`
    FOREIGN KEY (`Debates_idDebates`)
    REFERENCES `mydb`.`Debates` (`idDebates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Debates_has_Course_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
