-- MySQL Script generated by MySQL Workbench
-- 09/30/16 12:58:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `email` VARCHAR(20) NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `lastName2` VARCHAR(45) NULL,
  `idNumber` INT NULL,
  `idUniversity` INT NULL,
  `phone` INT NULL,
  `address` VARCHAR(45) NULL,
  `timeStamp` DATE NULL,
  `birthday` VARCHAR(45) NULL,
  `Userscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DebateTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DebateTypes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DebateTypes` (
  `idDebateTypes` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idDebateTypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DebateRules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DebateRules` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DebateRules` (
  `idDebateRules` INT NOT NULL,
  PRIMARY KEY (`idDebateRules`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Debates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Debates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Debates` (
  `idDebates` INT NOT NULL,
  `DebateTypes_idDebateTypes` INT NOT NULL,
  `DebateRules_idDebateRules` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `createdDate` DATE NULL,
  `startingDate` DATE NULL,
  `Debatescol` VARCHAR(45) NULL,
  PRIMARY KEY (`idDebates`),
  INDEX `fk_Debates_DebateTypes1_idx` (`DebateTypes_idDebateTypes` ASC),
  INDEX `fk_Debates_DebateRules1_idx` (`DebateRules_idDebateRules` ASC),
  CONSTRAINT `fk_Debates_DebateTypes1`
    FOREIGN KEY (`DebateTypes_idDebateTypes`)
    REFERENCES `mydb`.`DebateTypes` (`idDebateTypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Debates_DebateRules1`
    FOREIGN KEY (`DebateRules_idDebateRules`)
    REFERENCES `mydb`.`DebateRules` (`idDebateRules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ActiveDebates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ActiveDebates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ActiveDebates` (
  `idActiveDebates` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `Debates_idDebates` INT NOT NULL,
  PRIMARY KEY (`idActiveDebates`),
  INDEX `fk_ActiveDebates_Users_idx` (`Users_idUsers` ASC),
  INDEX `fk_ActiveDebates_Debates1_idx` (`Debates_idDebates` ASC),
  CONSTRAINT `fk_ActiveDebates_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActiveDebates_Debates1`
    FOREIGN KEY (`Debates_idDebates`)
    REFERENCES `mydb`.`Debates` (`idDebates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
